default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  
  template: template0
  username: ubuntu
  password: password
  
development:
  <<: *default
  database: user_base_development

test:
  <<: *default
  database: user_base_test

production:
  <<: *default
  database: user_base_production
  username: user_base
  password: <%= ENV['USER_BASE_DATABASE_PASSWORD'] %>