# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad8d3ae486540850058c1d35cecc16ef8d86e8526ff0e31be3732a67faf19ed70cae5f5e1d967c195af5f92fa73e262845c17b7ade2674303221bb36c222470c

test:
  secret_key_base: 78b3da1696120de1055480b4e6b439d5c7a7b8fb32dc0c7292f367c9fda772ea4dde0d7c73e4fed1f8e5586570aa32df9ac48435d630b6357b3af31d8c4fc3c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
